apiVersion: v1
kind: Service
metadata:
  name: etcd-viewer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8299
  selector:
    app: etcd-viewer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-viewer
  template:
    metadata:
      labels:
        app: etcd-viewer
    spec:
      containers:
      - name: etcd-viewer
        image: raushan2016/etcdexplore:8299-2
        env:
        - name: CA_FILE
          value: "/etc/kubernetes/pki/etcd/ca.crt"
        - name: CERT_FILE
          value: "/etc/kubernetes/pki/etcd/etcdclient.crt"
        - name: KEY_FILE
          value: "/etc/kubernetes/pki/etcd/etcdclient.key"
        - name: ENDPOINTS
          value: "https://127.0.0.1:2379"
        ports:
        - containerPort: 8299
        volumeMounts:
        - mountPath: /etc/kubernetes/pki/etcd
          name: etcd-certs
          readOnly: true
      nodeSelector:
        kubernetes.io/role: master
      tolerations:
      - effect: NoSchedule
        operator: Exists
      hostNetwork: true
      volumes:
      - name: etcd-certs
        hostPath:
          path: /etc/kubernetes/certs/
          type: DirectoryOrCreate