apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: model-mount-deployment
spec:
  selector:
    matchLabels:
      app: model-mount
  replicas: 1
  template:
    metadata:
      labels:
        app: model-mount
    spec:
      volumes:
      - name: model-volume
        emptyDir: {}
      - name: host-model-data
        hostPath:
          path: /mnt/modelData/
          type: DirectoryOrCreate
      initContainers:
      - name: model-init
        image: raushan2016/modelmount:latest
        imagePullPolicy: Always
        command: ["/model_download.sh",  "raushankdelete8410197315", "test", ".oml_package.zip"]
        volumeMounts:
        - name: host-model-data
          mountPath: "/models"
      containers:
      - name: model-service
        image: raushan2016/modelmount:latest
        imagePullPolicy: Always
        command: ["/model_service.sh"]
        volumeMounts:
        - name: host-model-data
          mountPath: /models